global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8889
  - job_name: otel-collector-self
    static_configs:
      - targets:
          - otel-collector:8888
  - job_name: nats
    metrics_path: /metrics
    static_configs:
      - targets:
          - nats-exporter:7777
  - job_name: redis
    static_configs:
      - targets:
          - redis-exporter:9121
  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets:
          - envoy:9901
  - job_name: result-store
    static_configs:
      - targets:
          - result-store:2222
  - job_name: worker
    static_configs:
      - targets:
          - worker:2222
  - job_name: ingest
    static_configs:
      - targets:
          - ingest:2222
  - job_name: enricher
    static_configs:
      - targets:
          - enricher:2222
  - job_name: scheduler
    static_configs:
      - targets:
          - scheduler:2222
  - job_name: audit
    static_configs:
      - targets:
          - audit:2222
  - job_name: notifier
    static_configs:
      - targets:
          - notifier:2222
  - job_name: deadletter
    static_configs:
      - targets:
          - deadletter:2222
